TARGET = libcef_dll_wrapper
TEMPLATE = lib

CEFDIR = ../../cef
INCLUDEPATH += $$CEFDIR
DEPENDPATH = $$CEFDIR

DEFINES += WINVER=0x0601 _WIN32_WINNT=0x601 NOMINMAX WIN32_LEAN_AND_MEAN _HAS_EXCEPTIONS=0 WRAPPING_CEF_SHARED

QMAKE_OBJECTIVE_CFLAGS += -wd4100 -wd4127 -wd4244 -wd4481 -wd4512 -wd4701 -wd4702 -wd4996

CONFIG += staticlib

PRECOMPILED_HEADER = stable.h
HEADERS += stable.h

CONFIG(debug, debug|release) {
    DESTDIR = ../../bin/debug
}
else {
    DESTDIR = ../../bin/release
}

HEADERS += $$CEFDIR/libcef_dll/ptr_util.h \
           $$CEFDIR/libcef_dll/shutdown_checker.h \
           $$CEFDIR/libcef_dll/transfer_util.h \
           $$CEFDIR/libcef_dll/wrapper_types.h \
           $$CEFDIR/libcef_dll/cpptoc/accessibility_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/app_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/audio_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/base_ref_counted_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/base_scoped_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/browser_process_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/client_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/completion_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/context_menu_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/cookie_access_filter_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/cookie_visitor_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/cpptoc_ref_counted.h \
           $$CEFDIR/libcef_dll/cpptoc/cpptoc_scoped.h \
           $$CEFDIR/libcef_dll/cpptoc/delete_cookies_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/dev_tools_message_observer_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/dialog_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/display_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/domvisitor_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/download_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/download_image_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/drag_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/end_tracing_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/extension_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/find_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/focus_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/jsdialog_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/keyboard_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/life_span_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/load_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/media_observer_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/media_route_create_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/media_sink_device_info_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/menu_model_delegate_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/navigation_entry_visitor_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/pdf_print_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/print_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/read_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/register_cdm_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/render_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/render_process_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/request_context_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/request_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/resolve_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/resource_bundle_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/resource_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/resource_request_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/response_filter_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/run_file_dialog_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/scheme_handler_factory_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/server_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/set_cookie_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/string_visitor_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/task_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/urlrequest_client_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/v8accessor_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/v8array_buffer_release_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/v8handler_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/v8interceptor_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/web_plugin_info_visitor_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/web_plugin_unstable_callback_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/write_handler_cpptoc.h \
           $$CEFDIR/libcef_dll/ctocpp/auth_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/before_download_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/binary_value_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/browser_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/browser_host_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/command_line_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/context_menu_params_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/cookie_manager_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/ctocpp_ref_counted.h \
           $$CEFDIR/libcef_dll/ctocpp/ctocpp_scoped.h \
           $$CEFDIR/libcef_dll/ctocpp/dictionary_value_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/domdocument_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/domnode_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/download_item_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/download_item_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/drag_data_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/extension_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/file_dialog_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/frame_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/get_extension_resource_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/image_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/jsdialog_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/list_value_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/media_route_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/media_router_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/media_sink_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/media_source_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/menu_model_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/navigation_entry_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/post_data_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/post_data_element_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/print_dialog_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/print_job_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/print_settings_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/process_message_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/registration_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/request_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/request_context_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/request_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/resource_bundle_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/resource_read_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/resource_skip_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/response_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/run_context_menu_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/scheme_registrar_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/select_client_certificate_callback_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/server_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/sslinfo_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/sslstatus_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/stream_reader_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/stream_writer_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/task_runner_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/thread_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/urlrequest_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/v8context_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/v8exception_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/v8stack_frame_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/v8stack_trace_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/v8value_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/value_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/waitable_event_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/web_plugin_info_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/x509cert_principal_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/x509certificate_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/xml_reader_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/zip_reader_ctocpp.h \
           $$CEFDIR/libcef_dll/wrapper/cef_browser_info_map.h \
           $$CEFDIR/libcef_dll/cpptoc/test/translator_test_ref_ptr_client_child_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/test/translator_test_ref_ptr_client_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/test/translator_test_scoped_client_child_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/test/translator_test_scoped_client_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/views/browser_view_delegate_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/views/button_delegate_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/views/menu_button_delegate_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/views/panel_delegate_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/views/textfield_delegate_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/views/view_delegate_cpptoc.h \
           $$CEFDIR/libcef_dll/cpptoc/views/window_delegate_cpptoc.h \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_ref_ptr_library_child_child_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_ref_ptr_library_child_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_ref_ptr_library_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_scoped_library_child_child_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_scoped_library_child_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_scoped_library_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/box_layout_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/browser_view_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/button_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/display_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/fill_layout_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/label_button_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/layout_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/menu_button_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/menu_button_pressed_lock_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/panel_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/scroll_view_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/textfield_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/view_ctocpp.h \
           $$CEFDIR/libcef_dll/ctocpp/views/window_ctocpp.h
SOURCES += $$CEFDIR/libcef_dll/shutdown_checker.cc \
           $$CEFDIR/libcef_dll/transfer_util.cc \
           $$CEFDIR/libcef_dll/base/cef_atomicops_x86_gcc.cc \
           $$CEFDIR/libcef_dll/base/cef_bind_helpers.cc \
           $$CEFDIR/libcef_dll/base/cef_callback_helpers.cc \
           $$CEFDIR/libcef_dll/base/cef_callback_internal.cc \
           $$CEFDIR/libcef_dll/base/cef_lock.cc \
           $$CEFDIR/libcef_dll/base/cef_lock_impl.cc \
           $$CEFDIR/libcef_dll/base/cef_logging.cc \
           $$CEFDIR/libcef_dll/base/cef_ref_counted.cc \
           $$CEFDIR/libcef_dll/base/cef_string16.cc \
           $$CEFDIR/libcef_dll/base/cef_thread_checker_impl.cc \
           $$CEFDIR/libcef_dll/base/cef_weak_ptr.cc \
           $$CEFDIR/libcef_dll/cpptoc/accessibility_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/app_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/audio_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/base_ref_counted_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/base_scoped_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/browser_process_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/client_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/completion_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/context_menu_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/cookie_access_filter_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/cookie_visitor_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/delete_cookies_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/dev_tools_message_observer_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/dialog_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/display_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/domvisitor_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/download_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/download_image_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/drag_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/end_tracing_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/extension_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/find_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/focus_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/jsdialog_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/keyboard_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/life_span_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/load_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/media_observer_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/media_route_create_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/media_sink_device_info_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/menu_model_delegate_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/navigation_entry_visitor_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/pdf_print_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/print_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/read_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/register_cdm_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/render_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/render_process_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/request_context_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/request_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/resolve_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/resource_bundle_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/resource_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/resource_request_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/response_filter_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/run_file_dialog_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/scheme_handler_factory_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/server_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/set_cookie_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/string_visitor_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/task_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/urlrequest_client_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/v8accessor_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/v8array_buffer_release_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/v8handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/v8interceptor_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/web_plugin_info_visitor_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/web_plugin_unstable_callback_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/write_handler_cpptoc.cc \
           $$CEFDIR/libcef_dll/ctocpp/auth_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/before_download_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/binary_value_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/browser_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/browser_host_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/command_line_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/context_menu_params_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/cookie_manager_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/dictionary_value_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/domdocument_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/domnode_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/download_item_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/download_item_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/drag_data_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/extension_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/file_dialog_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/frame_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/get_extension_resource_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/image_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/jsdialog_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/list_value_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/media_route_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/media_router_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/media_sink_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/media_source_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/menu_model_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/navigation_entry_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/post_data_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/post_data_element_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/print_dialog_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/print_job_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/print_settings_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/process_message_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/registration_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/request_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/request_context_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/request_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/resource_bundle_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/resource_read_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/resource_skip_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/response_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/run_context_menu_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/scheme_registrar_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/select_client_certificate_callback_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/server_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/sslinfo_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/sslstatus_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/stream_reader_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/stream_writer_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/task_runner_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/thread_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/urlrequest_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/v8context_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/v8exception_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/v8stack_frame_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/v8stack_trace_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/v8value_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/value_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/waitable_event_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/web_plugin_info_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/x509cert_principal_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/x509certificate_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/xml_reader_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/zip_reader_ctocpp.cc \
           $$CEFDIR/libcef_dll/wrapper/cef_byte_read_handler.cc \
           $$CEFDIR/libcef_dll/wrapper/cef_closure_task.cc \
           $$CEFDIR/libcef_dll/wrapper/cef_message_router.cc \
           $$CEFDIR/libcef_dll/wrapper/cef_resource_manager.cc \
           $$CEFDIR/libcef_dll/wrapper/cef_scoped_temp_dir.cc \
           $$CEFDIR/libcef_dll/wrapper/cef_stream_resource_handler.cc \
           $$CEFDIR/libcef_dll/wrapper/cef_xml_object.cc \
           $$CEFDIR/libcef_dll/wrapper/cef_zip_archive.cc \
           $$CEFDIR/libcef_dll/wrapper/libcef_dll_wrapper.cc \
           $$CEFDIR/libcef_dll/wrapper/libcef_dll_wrapper2.cc \
           $$CEFDIR/libcef_dll/cpptoc/test/translator_test_ref_ptr_client_child_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/test/translator_test_ref_ptr_client_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/test/translator_test_scoped_client_child_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/test/translator_test_scoped_client_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/views/browser_view_delegate_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/views/button_delegate_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/views/menu_button_delegate_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/views/panel_delegate_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/views/textfield_delegate_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/views/view_delegate_cpptoc.cc \
           $$CEFDIR/libcef_dll/cpptoc/views/window_delegate_cpptoc.cc \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_ref_ptr_library_child_child_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_ref_ptr_library_child_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_ref_ptr_library_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_scoped_library_child_child_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_scoped_library_child_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/test/translator_test_scoped_library_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/box_layout_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/browser_view_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/button_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/display_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/fill_layout_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/label_button_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/layout_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/menu_button_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/menu_button_pressed_lock_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/panel_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/scroll_view_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/textfield_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/view_ctocpp.cc \
           $$CEFDIR/libcef_dll/ctocpp/views/window_ctocpp.cc
